.\" Man page for XPS (eXquisite Port Seeker)
.\" Contact anastasiadis@datalive.gr to correct errors or omissions.
.TH xps 1 "04 December 2008" "0.41"

.SH NAME
xps - eXquisite Port Seeker

.SH SYNOPSIS
xps [options] terms
.SH DESCRIPTION
xps is a tool that searches the ports INDEX file and prints all ports whose names contain the given terms and match the specified criterias.
.P
The default mode prints a line for each port found. The brackets in the beginning of each line show the port's status:
.IP "'i'"
the port is installed
.IP "'u'"
the port is installed and can be updated
.SH EXAMPLES
.P
Show all ports whose names contain 'firefox' and print verbose descriptions:
.IP
xps -v firefox
.P
Show all ports in category 'devel' with exact name 'python'.
.IP
xps -e -c devel python
.P
Show all ports whose names contain 'glib' and are installed:
.IP
xps -i yes glib
.P
Show all ports maintained by <author> in category <category>:
.IP
xps -m <author> -c <category>
.P
Show all ports that contain 'pdf' in thier short description:
.IP
xps -D pdf
.P
Show ports whose name starts with 'gnome':
.IP
xps -E '^gnome'
.SH OPTIONS
.IP "-c <category>"
Show ports only from this category.
.IP "-e"
Exact match. Show only ports that their name is an exact match of the given term.
.IP "-i yes/no"
Show only installed/non-installed ports.
.IP "-u yes/no"
Show ports that are installed and can/cannot be updated.
.IP "-m <maintainer>"
Show only ports maintained by <maintainer>.
.IP "-v"
Show verbose descriptions.
.IP "-E <regex>"
Show ports that thier name matches given regular expression.
.IP "-D <string>"
Show ports whose short description contain given string.
.IP "-DE <regex>"
Show ports whose short description match given regular expression.
.IP "-s"
Print port statistics and exit.
.IP "--version"
Show program version and exit.
.SH BUGS
.P
* The code that matches installed packages with indexed ports needs a lot of work, expect bugs in this area.
.P
* xps is broken in systems migrated to pkgng. Expect this to be solved in a newer version.
.SH AUTHOR
.nf
Antonios Anastasiadis (anastasiadis@datalive.gr)
.fi
